name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Code Clone from GitHub"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build Docker Container
        run: echo "Docker Container Build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test the Container
        run: echo "Testing the container"