name: CICD Pipeline 

on:
  workflow_dispatch:
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code Clone from GitHub"
    build:
      runs-on: ubuntu-latest
       steps:
         - name: Build Docker Container
           run: echo "Docker Container Build"
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Test the container
          run: echo "Testing the container"
          
    
